version: '3.4'

services:

  elasticsearch:
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node

  kibana:
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200

  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
   
  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin12345

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb=mongodb://catalog.db:27017
      - ElasticConfiguration__Uri=http://elasticsearch:9200

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=basket.db:6379
      - ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672
      - DiscountSettings__GrpcUrl=http://discount.grpc
      - ElasticConfiguration__Uri=http://elasticsearch:9200

  discount.db:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin12345
      - POSTGRES_DB=DiscountDb
  discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgreSQL=Server=discount.db;Port=5432;Database=DiscountDb;User Id=admin;Password=admin12345;
      - ElasticConfiguration__Uri=http://elasticsearch:9200
  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgreSQL=Server=discount.db;Port=5432;Database=DiscountDb;User Id=admin;Password=admin12345;
      - ElasticConfiguration__Uri=http://elasticsearch:9200

  order.db:
    environment:
        SA_PASSWORD: "admin12345"
        ACCEPT_EULA: "Y"

  order.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=order.db;Database=OrderDb;User Id=sa;Password=admin12345;TrustServerCertificate=true;
      - ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672
      - ElasticConfiguration__Uri=http://elasticsearch:9200

  ocelot.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ElasticConfiguration__Uri=http://elasticsearch:9200

  microrestaurant.aggregator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings__CatalogUrl=http://catalog.api
      - ApiSettings__BasketUrl=http://basket.api
      - ApiSettings__OrderUrl=http://order.api
      - ElasticConfiguration__Uri=http://elasticsearch:9200