version: '3.4'

services:

  jaeger:
    environment:
    - SPAN_STORAGE_TYPE=badger
    - BADGER_EPHEMERAL=false
    - BADGER_DIRECTORY_VALUE=/badger/data
    - BADGER_DIRECTORY_KEY=/badger/key

  elasticsearch:
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node

  kibana:
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200

  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
   
  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin12345

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb=mongodb://catalog.db:27017
      - ElasticConfiguration__Endpoint=http://elasticsearch:9200
      - ZipkinConfiguration__Endpoint=http://zipkin:9411/api/v2/spans
      - JaegerConfiguration__Endpoint=jaeger:6831

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=basket.db:6379
      - ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672
      - DiscountSettings__GrpcUrl=http://discount.grpc
      - ElasticConfiguration__Endpoint=http://elasticsearch:9200
      - ZipkinConfiguration__Endpoint=http://zipkin:9411/api/v2/spans
      - JaegerConfiguration__Endpoint=jaeger:6831

  discount.db:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin12345
      - POSTGRES_DB=DiscountDb
  discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgreSQL=Server=discount.db;Port=5432;Database=DiscountDb;User Id=admin;Password=admin12345;
      - ElasticConfiguration__Endpoint=http://elasticsearch:9200
      - ZipkinConfiguration__Endpoint=http://zipkin:9411/api/v2/spans
      - JaegerConfiguration__Endpoint=jaeger:6831
  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgreSQL=Server=discount.db;Port=5432;Database=DiscountDb;User Id=admin;Password=admin12345;
      - ElasticConfiguration__Endpoint=http://elasticsearch:9200
      - ZipkinConfiguration__Endpoint=http://zipkin:9411/api/v2/spans
      - JaegerConfiguration__Endpoint=jaeger:6831

  order.db:
    environment:
        SA_PASSWORD: "admin12345"
        ACCEPT_EULA: "Y"

  order.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=order.db;Database=OrderDb;User Id=sa;Password=admin12345;TrustServerCertificate=true;
      - ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672
      - ElasticConfiguration__Endpoint=http://elasticsearch:9200
      - ZipkinConfiguration__Endpoint=http://zipkin:9411/api/v2/spans
      - JaegerConfiguration__Endpoint=jaeger:6831

  ocelot.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ElasticConfiguration__Endpoint=http://elasticsearch:9200
      - ZipkinConfiguration__Endpoint=http://zipkin:9411/api/v2/spans
      - JaegerConfiguration__Endpoint=jaeger:6831

  microrestaurant.aggregator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings__CatalogUrl=http://catalog.api
      - ApiSettings__BasketUrl=http://basket.api
      - ApiSettings__OrderUrl=http://order.api
      - ElasticConfiguration__Endpoint=http://elasticsearch:9200
      - ZipkinConfiguration__Endpoint=http://zipkin:9411/api/v2/spans
      - JaegerConfiguration__Endpoint=jaeger:6831