version: '3.4'

services:

  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
   
  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin12345

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb=mongodb://catalog.db:27017

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=basket.db:6379
      - DiscountSettings__GrpcUrl=http://discount.grpc

  discount.db:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin12345
      - POSTGRES_DB=DiscountDb
  discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgreSQL=Server=discount.db;Port=5432;Database=DiscountDb;User Id=admin;Password=admin12345;
  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgreSQL=Server=discount.db;Port=5432;Database=DiscountDb;User Id=admin;Password=admin12345;

  order.db:
    environment:
        SA_PASSWORD: "admin12345"
        ACCEPT_EULA: "Y"

  order.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=order.db;Database=OrderDb;User Id=sa;Password=admin12345;TrustServerCertificate=true;
