version: '3.4'

name: MicroRestaurant

services:
  
  catalog.db:
    container_name: catalog.db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalog.api:
    container_name: catalog.api
    image: ${DOCKER_REGISTRY-}catalogapi
    ports:
      - "8000:80"
    depends_on:
        - catalog.db
    build:
      context: .
      dockerfile: src/Catalog/Catalog.Api/Dockerfile

  #mongoclient:
  #    image: mongoclient/mongoclient:latest
  #    container_name: mongoclient
  #    hostname: mongoclient
  #    depends_on:
  #      - catalog.db
  #    ports:
  #      - 3300:3000

volumes:

  mongo_data: